const CreateTypes = {
  CREATE_BUSINESS_REQUEST: "CREATE_BUSINESS_REQUEST",
  CREATE_BUSINESS_SUCCESS: "CREATE_BUSINESS_SUCCESS",
  CREATE_BUSINESS_FAILURE: "CREATE_BUSINESS_FAILURE",
  CREATE_BUSINESS_PROGRESS: "CREATE_BUSINESS_PROGRESS",
};

export default CreateTypes;